"""유틸리티 모듈"""
from utils.claude_client import (
    get_client,
    generate_response,
    generate_titles,
    generate_toc,
    generate_draft,
    get_feedback,
    refine_text,
    add_storytelling,
    chat_with_coach,
    edit_draft_with_instruction,
    generate_proposal,
    generate_landing_page,
    analyze_youtube_transcript,
    generate_titles_from_transcript,
    generate_toc_from_transcript,
    generate_draft_from_transcript,
)

from utils.voice_handler import (
    transcribe_audio,
    validate_audio_file,
    get_file_extension,
    render_voice_mode_ui,
    render_microphone_input,
    render_file_upload_input,
    render_transcription_editor,
    clear_voice_session,
)

from utils.youtube_handler import (
    extract_video_id,
    get_video_info,
    get_transcript,
    get_transcript_with_timestamps,
    format_timestamp,
    chunk_transcript,
    process_multiple_videos,
    merge_transcripts_for_book,
)

from utils.contact_handler import (
    get_admin_settings,
    ensure_data_directory,
    save_message_to_csv,
    save_message_to_json,
    load_all_messages_json,
    load_all_messages_csv,
    update_message_status,
    get_step_name,
    get_pending_messages_count,
    get_student_messages,
    render_contact_button,
    render_message_form,
    render_my_questions,
    render_contact_section,
)

from utils.help_chatbot import (
    STEP_CONTEXTS,
    FAQ_QUESTIONS,
    get_step_context,
    get_contextual_help,
    render_floating_chatbot_button,
    render_enhanced_chatbot,
    render_help_sidebar_button,
    init_help_chatbot_state,
)

from utils.autosave_handler import (
    ensure_autosave_directory,
    save_progress,
    load_backup,
    delete_backup,
    get_all_backups,
    get_student_backups,
    check_for_previous_work,
    should_autosave,
    get_time_since_last_save,
    format_backup_info,
    restore_session_data,
    render_autosave_status,
    render_save_buttons,
    render_backup_list,
    render_recovery_prompt,
    perform_autosave_if_needed,
    trigger_important_save,
    init_autosave_state,
)

from utils.mode_transition import (
    transfer_chat_mode_to_normal,
    transfer_voice_mode_to_normal,
    transfer_youtube_mode_to_normal,
    safe_mode_transition,
    restore_from_mode_transition,
    handle_api_error,
    init_mode_transition_state,
    determine_next_step,
)

__all__ = [
    # claude_client
    "get_client",
    "generate_response",
    "generate_titles",
    "generate_toc",
    "generate_draft",
    "get_feedback",
    "refine_text",
    "add_storytelling",
    "chat_with_coach",
    "edit_draft_with_instruction",
    "generate_proposal",
    "generate_landing_page",
    "analyze_youtube_transcript",
    "generate_titles_from_transcript",
    "generate_toc_from_transcript",
    "generate_draft_from_transcript",
    # voice_handler
    "transcribe_audio",
    "validate_audio_file",
    "get_file_extension",
    "render_voice_mode_ui",
    "render_microphone_input",
    "render_file_upload_input",
    "render_transcription_editor",
    "clear_voice_session",
    # youtube_handler
    "extract_video_id",
    "get_video_info",
    "get_transcript",
    "get_transcript_with_timestamps",
    "format_timestamp",
    "chunk_transcript",
    "process_multiple_videos",
    "merge_transcripts_for_book",
    # contact_handler
    "get_admin_settings",
    "ensure_data_directory",
    "save_message_to_csv",
    "save_message_to_json",
    "load_all_messages_json",
    "load_all_messages_csv",
    "update_message_status",
    "get_step_name",
    "get_pending_messages_count",
    "get_student_messages",
    "render_contact_button",
    "render_message_form",
    "render_my_questions",
    "render_contact_section",
    # help_chatbot
    "STEP_CONTEXTS",
    "FAQ_QUESTIONS",
    "get_step_context",
    "get_contextual_help",
    "render_floating_chatbot_button",
    "render_enhanced_chatbot",
    "render_help_sidebar_button",
    "init_help_chatbot_state",
    # autosave_handler
    "ensure_autosave_directory",
    "save_progress",
    "load_backup",
    "delete_backup",
    "get_all_backups",
    "get_student_backups",
    "check_for_previous_work",
    "should_autosave",
    "get_time_since_last_save",
    "format_backup_info",
    "restore_session_data",
    "render_autosave_status",
    "render_save_buttons",
    "render_backup_list",
    "render_recovery_prompt",
    "perform_autosave_if_needed",
    "trigger_important_save",
    "init_autosave_state",
    # mode_transition
    "transfer_chat_mode_to_normal",
    "transfer_voice_mode_to_normal",
    "transfer_youtube_mode_to_normal",
    "safe_mode_transition",
    "restore_from_mode_transition",
    "handle_api_error",
    "init_mode_transition_state",
    "determine_next_step",
]
